### PR TITLE
Bump remap-istanbul version

### PR DESCRIPTION
**Pull request by marines**
This version of remap-istanbul introduces fix to absolute paths in source maps.

### CODE REVIEW

**Comment by marines** [comment]
@marcules buddy, you there?

**Comment by delasteve** [comment]
I tested this with the `angular-cli` and it fixes issues I was having with it. Please consider merging this!

**Comment by dumbNickname** [comment]
I have also tested this upgrade and it works fine, would be nice to see that merged.

**Comment by marcules** [comment]
Sorry for being so unresponsive you guys, but I'm currently drowning in
work. I've added Stephen as a collaborator so things can get done while I'm
unavailable.

Cheers, Marc

Bartek Pietrowski notifications@github.com schrieb am Di., 24. Mai 2016,
15:19:

**Comment by delasteve** [comment]
Thanks @marcules.

I have released `0.0.6` of this repo. It includes this PR.

Enjoy!

**Pull request merged**
